apiVersion: v1
kind: Service
metadata:
  name: {{ include "sonatype-nexus.fullname" . }}
  labels:
    {{- include "sonatype-nexus.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http-web
      port: {{ .Values.nexus.nexusPort }}
    - name: http-docker
      port: {{ .Values.nexus.dockerPort }}
  selector:
    {{- include "sonatype-nexus.selectorLabels" . | nindent 4 }}
