# https://github.com/helm/chart-testing#configuration
debug: false
remote: origin
target-branch: main
chart-dirs:
  - charts
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
  - gitlab=https://charts.gitlab.io
helm-extra-args: --timeout 600s
